Checkov print only CHECK: FAILS

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -15,26 +15,28 @@ jobs:
       contents: read  # for actions/checkout to fetch code
       # security-events: write  # Commented out as it requires GitHub Advanced Security
     runs-on: ubuntu-latest
+
     steps:
       - name: Clear Cache
-        uses: actions/cache@v4.0.2 # v4.0.2
+        uses: actions/cache@v4.0.2
         with:
-         path: |
-           ./.github/workflows/
-         key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
-         restore-keys: |
-           ${{ runner.os }}-workflow-${{ github.event_name }}-       
+          path: |
+            ./.github/workflows/
+          key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-workflow-${{ github.event_name }}-
 
       - name: Harden Runner
-        uses: step-security/harden-runner@v2.8.1 # v2.8.1
+        uses: step-security/harden-runner@v2.8.1
         with:
           egress-policy: audit
 
-      - uses: actions/checkout@v4.1.7 # v4.1.7
+      - name: Checkout Code
+        uses: actions/checkout@v4.1.7
 
       - name: Checkov Scan
         id: checkov_scan
-        uses: bridgecrewio/checkov-action@v12.1347.0 # v12.1347.0
+        uses: bridgecrewio/checkov-action@v12.1347.0
         with:
           directory: '.'  # Root directory to scan (adjust if needed)
           output_format: 'json'  # Output format (cli, json, junit_xml, sarif)
@@ -48,27 +50,27 @@ jobs:
         id: check_results
         run: |
           if [[ -s checkov_results.json ]]; then
-            echo "results_exist=true" >> $GITHUB_OUTPUT
+            echo "results_exist=true" >> $GITHUB_ENV
           else
-            echo "results_exist=false" >> $GITHUB_OUTPUT
+            echo "results_exist=false" >> $GITHUB_ENV
           fi
 
       - name: Checkov Passed Checks (If Any)
-        if: steps.check_results.outputs.results_exist == 'true'
+        if: env.results_exist == 'true'
         run: |
           echo "Checkov Scan Results (Passed Checks Only):"
           # Filter only passed checks using jq
-          jq -r '.results[] | select(.result=="PASSED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true 
+          jq -r '.results[] | select(.result=="PASSED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true
 
-      - name: Checkovy Failed Checks (If Any)
-        if: steps.check_results.outputs.results_exist == 'true' && steps.checkov_scan.outcome != 'success'  # Only run if there are failures
+      - name: Checkov Failed Checks (If Any)
+        if: env.results_exist == 'true' && steps.checkov_scan.outcome != 'success'  # Only run if there are failures
         run: |
           echo "Checkov Scan Results (Failed Checks Only):"
           # Filter only failed checks using jq
-          jq -r '.results[] | select(.result=="FAILED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true 
+          jq -r '.results[] | select(.result=="FAILED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true
 
       - name: Handle Empty Results
-        if: steps.check_results.outputs.results_exist == 'false'
+        if: env.results_exist == 'false'
         run: |
           echo "Warning: Checkov did not find any resources to scan."
 
@@ -79,6 +81,6 @@ jobs:
       # Commented out the step that requires GitHub Advanced Security
       # - name: Upload SARIF file (optional)
       #   if: always()  # Always run this step, even if previous steps fail
-      #   uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
+      #   uses: github/codeql-action/upload-sarif@v3.25.8
       #   with:
       #     sarif_file: 'results.sarif'  # SARIF output file name (adjust if needed)
