Block Changes to .github Directory and Improve Checkov to print CHECK: FAILS

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -23,15 +23,26 @@ jobs:
         with:
           egress-policy: audit
 
-      - uses: actions/checkout@v4.1.6 # v4.1.6
+      - uses: actions/checkout@v4.1.7 # v4.1.7
 
       - name: Checkov Scan
         id: checkov_scan
-        uses: bridgecrewio/checkov-action@v12.2777.0 # v12.2777.0
+        uses: bridgecrewio/checkov-action@v12.1347.0 # v12.1347.0
         with:
           directory: '.'  # Root directory to scan (adjust if needed)
-          output_format: 'cli'  # Output format (cli, json, junit_xml, sarif)
+          output_format: 'json'  # Output format (cli, json, junit_xml, sarif)
           # Add other Checkov configuration options here if necessary
+
+      - name: Extract and Display Failed Checks
+        if: always()  # Always run this step, even if previous steps fail
+        run: |
+          echo "Checkov Scan Results (Failed Checks Only):"
+          echo "${{ steps.checkov_scan.outputs.results }}" | jq -r '.results.failed_checks[] | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"'
+          
+      - name: Fail on Checkov Errors
+        if: steps.checkov_scan.outcome == 'failure' && !contains(github.event_name, 'pull_request')
+        run: exit 1  # This will fail the workflow if Checkov finds errors during a push
+
 
       # Commented out the step that requires GitHub Advanced Security
       # - name: Upload SARIF file (optional)
