Checkov separately print CHECKS: PASSED/FAILS

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -1,86 +1,85 @@
-on:
-  push:
-    branches:
-      - aws-dev
-  pull_request:
-    branches:
-      - aws-dev
+  on:
+    push:
+      branches:
+        - aws-dev
+    pull_request:
+      branches:
+        - aws-dev
 
-permissions:
-  contents: read
+  jobs:
+    checkov_scan:
+      permissions:
+        contents: read  # for actions/checkout to fetch code
+        # security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+        # actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+      runs-on: ubuntu-latest
 
-jobs:
-  checkov_scan:
-    permissions:
-      contents: read  # for actions/checkout to fetch code
-      # security-events: write  # Commented out as it requires GitHub Advanced Security
-    runs-on: ubuntu-latest
+      steps:
+        - name: Clear Cache
+          uses: actions/cache@v4.0.2
+          with:
+            path: |
+              ./.github/workflows/
+            key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
+            restore-keys: |
+              ${{ runner.os }}-workflow-${{ github.event_name }}-
 
-    steps:
-      - name: Clear Cache
-        uses: actions/cache@v4.0.2
-        with:
-          path: |
-            ./.github/workflows/
-          key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-workflow-${{ github.event_name }}-
+        - name: Harden Runner
+          uses: step-security/harden-runner@v2.8.1
+          with:
+            egress-policy: audit
 
-      - name: Harden Runner
-        uses: step-security/harden-runner@v2.8.1
-        with:
-          egress-policy: audit
+        - name: Checkout Code
+          uses: actions/checkout@v4.1.7
 
-      - name: Checkout Code
-        uses: actions/checkout@v4.1.7
+        - name: Checkov Scan
+          id: checkov_scan
+          uses: bridgecrewio/checkov-action@v12.2784.0
+          with:
+            directory: '.'  # Root directory to scan (adjust if needed)
+            output_format: json  # Output format (cli, json, junit_xml, sarif)
+            output_file_path: console
+            # Add other Checkov configuration options here if necessary
 
-      - name: Checkov Scan
-        id: checkov_scan
-        uses: bridgecrewio/checkov-action@v12.1347.0
-        with:
-          directory: '.'  # Root directory to scan (adjust if needed)
-          output_format: 'json'  # Output format (cli, json, junit_xml, sarif)
-          # Add other Checkov configuration options here if necessary
+        - name: Save Checkov Results to File
+          if: always()
+          run: echo "${{ steps.checkov_scan.outputs.results }}" > checkov_results.json
 
-      - name: Save Checkov Results to File
-        if: always()
-        run: echo "${{ steps.checkov_scan.outputs.results }}" > checkov_results.json
+        - name: Check for Empty Results
+          id: check_results
+          run: |
+            if [[ -s checkov_results.json ]]; then
+              echo "results_exist=true" >> $GITHUB_ENV
+            else
+              echo "results_exist=false" >> $GITHUB_ENV
+            fi
 
-      - name: Check for Empty Results
-        id: check_results
-        run: |
-          if [[ -s checkov_results.json ]]; then
-            echo "results_exist=true" >> $GITHUB_ENV
-          else
-            echo "results_exist=false" >> $GITHUB_ENV
-          fi
+        - name: Checkov Passed Checks (If Any)
+          if: steps.checkov_scan.outcome == 'success' && steps.checkov_scan.outcome != 'failure'
+          run: |
+            echo "Checkov Scan Results (Passed Checks Only):"
+            # Filter only passed checks using jq
+            jq -r '.results[] | select(.result=="PASSED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true
 
-      - name: Checkov Passed Checks (If Any)
-        if: env.results_exist == 'true'
-        run: |
-          echo "Checkov Scan Results (Passed Checks Only):"
-          # Filter only passed checks using jq
-          jq -r '.results[] | select(.result=="PASSED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true
+        - name: Checkov Failed Checks (If Any)
+          if: steps.checkov_scan.outcome == 'failure'
+          run: |
+            echo "Checkov Scan Results (Failed Checks Only):"
+            # Filter only failed checks using jq
+            jq -r '.results[] | select(.result=="FAILED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true
 
-      - name: Checkov Failed Checks (If Any)
-        if: env.results_exist == 'true' && steps.checkov_scan.outcome != 'success'  # Only run if there are failures
-        run: |
-          echo "Checkov Scan Results (Failed Checks Only):"
-          # Filter only failed checks using jq
-          jq -r '.results[] | select(.result=="FAILED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true
+        - name: Handle Empty Results
+          if: steps.checkov_scan.outcome == 'success' && steps.checkov_scan.outcome != 'failure' && env.results_exist == 'false'
+          run: |
+            echo "Warning: Checkov did not find any resources to scan."
 
-      - name: Handle Empty Results
-        if: env.results_exist == 'false'
-        run: |
-          echo "Warning: Checkov did not find any resources to scan."
+        - name: Fail on Checkov Errors (Push Only)
+          if: steps.checkov_scan.outcome == 'failure' && !contains(github.event_name, 'pull_request')
+          run: exit 1
 
-      - name: Fail on Checkov Errors (Push Only)
-        if: steps.checkov_scan.outcome == 'failure' && !contains(github.event_name, 'pull_request')
-        run: exit 1
-
-      # Commented out the step that requires GitHub Advanced Security
-      # - name: Upload SARIF file (optional)
-      #   if: always()  # Always run this step, even if previous steps fail
-      #   uses: github/codeql-action/upload-sarif@v3.25.8
-      #   with:
-      #     sarif_file: 'results.sarif'  # SARIF output file name (adjust if needed)
+        # Commented out the step that requires GitHub Advanced Security
+        # - name: Upload SARIF file (optional)
+        #   if: always()  # Always run this step, even if previous steps fail
+        #   uses: github/codeql-action/upload-sarif@v3.25.8
+        #   with:
+        #     sarif_file: 'results.sarif'  # SARIF output file name (adjust if needed)
