ubpg8

diff --git a/.github/workflows/enforce-branch-sequence.yml b/.github/workflows/enforce-branch-sequence.yml
--- a/.github/workflows/enforce-branch-sequence.yml
+++ b/.github/workflows/enforce-branch-sequence.yml
@@ -4,6 +4,10 @@ on:
   pull_request_target:
     types: [opened, reopened, synchronize]
 
+permissions:  
+  contents: read
+  pull-requests: write
+
 jobs:
   check_branch_sequence:
     runs-on: ubuntu-latest
@@ -22,23 +26,25 @@ jobs:
          restore-keys: |
            ${{ runner.os }}-workflow-${{ github.event_name }}-                
 
-      - name: Check Branch Sequence
-        uses: actions/github-script@v7.0.1
-        with:
-          script: |
-            const headBranch = context.payload.pull_request.head.ref;
-            const baseBranch = context.payload.pull_request.base.ref;
-            const allowedTransitions = [
-              ['aws-dev', 'staging'],
-              ['staging', 'master']
-            ];
-
-            const isValidTransition = allowedTransitions.some(
-              ([source, target]) => headBranch === source && baseBranch === target
-            );
-
-            if (!isValidTransition) {
-              throw new Error(
-                `Invalid branch transition: Pull requests are only allowed from aws-dev to staging and from staging to master.`
-              );
-            }
+      - name: Enforce Branch Sequence
+        run: |
+          # Get source and target branches
+          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
+          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
+     
+          # Define allowed transitions
+          if [[ "$TARGET_BRANCH" == "aws-dev" ]]; then
+           # Any branch is allowed to merge into aws-dev
+           echo "Branch sequence is valid."
+          elif [[ "$TARGET_BRANCH" == "staging" && "$SOURCE_BRANCH" == "aws-dev" ]]; then
+            echo "Branch sequence is valid."
+          elif [[ "$TARGET_BRANCH" == "master" && "$SOURCE_BRANCH" == "staging" ]]; then
+            echo "Branch sequence is valid."
+          else
+            echo "Error: Invalid branch sequence. PRs can only be made from:"
+            echo "  * Any branch to 'aws-dev'"
+            echo "  * 'aws-dev' to 'staging'"
+            echo "  * 'staging' to 'master'"
+            exit 1 
+          fi
+          
