UpdateBranchSequence3

diff --git a/.github/workflows/test-branch-sequence.yml b/.github/workflows/test-branch-sequence.yml
--- a/.github/workflows/test-branch-sequence.yml
+++ b/.github/workflows/test-branch-sequence.yml
@@ -1,4 +1,4 @@
-name: Branch Sequence & Permissions Testing
+name: Test Branch Sequence and Permissions
 
 on:
   push:
@@ -17,14 +17,15 @@ on:
   pull_request_target:
 
 permissions:
-  contents: read  
+  contents: read
 
 jobs:
-  clear-cache:   
+
+  clear-cache:
     runs-on: ubuntu-latest
     steps:
       - name: Clear Cache
-        uses: actions/cache@v4
+        uses: actions/cache@v2
         with:
           path: |
             ./.github/workflows/
@@ -32,19 +33,17 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-workflow-${{ github.event_name }}-
 
-  test-branch-sequence:    
+  
+  test-branch-sequence:
     runs-on: ubuntu-latest
     steps:
       - name: Harden Runner
-        uses: step-security/harden-runner@v2.8.0
+        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
         with:
           egress-policy: audit
 
       - name: Checkout Code
-        uses: actions/checkout@v3.6.0  
-
-      - name: Install tree 
-        run: sudo apt-get install -y tree
+        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
 
       - name: Verify working directory
         run: pwd
@@ -59,12 +58,12 @@ jobs:
         run: ls -la ./.github/workflows/scripts
 
       - name: Check if test script exists
-        run: test -f ./.github/workflows/scripts/enforce-branch-sequence-test.sh && echo "File exists" || echo "File does not exist"                      
+        run: test -f ./.github/workflows/scripts/enforce-branch-sequence-test.sh && echo "File exists" || echo "File does not exist"        
 
       - name: Make tests scripts executable
         run: |
-          chmod +x ./.github/workflows/scripts/enforce-branch-sequence-test.sh
           chmod +x ./.github/workflows/scripts/common_functions.sh
+          chmod +x ./.github/workflows/scripts/enforce-branch-sequence-test.sh
           chmod +x ./.github/workflows/scripts/01-direct-push-master.sh
           chmod +x ./.github/workflows/scripts/02-direct-push-staging.sh
           chmod +x ./.github/workflows/scripts/03-direct-push-aws-dev.sh
@@ -78,46 +77,24 @@ jobs:
 
       - name: Run Branch Sequence Tests
         run: |
-          failed_scripts=() # Initialize an array to store failed scripts
-          for i in {1..6}; do  
-            script="0${i}-*.sh"
-            if [ -f "$script" ]; then
-              echo "Running: $script"
-              ENFORCE_BRANCH_SEQUENCE_FILE="$GITHUB_WORKSPACE/.github/workflows/enforce-branch-sequence.yml" 
-              if ! bash "$script" "$ENFORCE_BRANCH_SEQUENCE_FILE"; then  
-                echo "Error: $script failed. Check the script output for details."
-                failed_scripts+=("$script")  # Add the failed script to the array
-              else
-                echo "Success: $script passed."  
-              fi
-            else
-              echo "Skipping: $script not found."  
-            fi
-          done
+          ./.github/workflows/scripts/enforce-branch-sequence-test.sh || echo "Branch sequence tests failed."
 
-          # Report failures at the end (if any)
-          if [ "${#failed_scripts[@]}" -gt 0 ]; then
-            echo "Errors found in the following scripts:"
-            for failed_script in "${failed_scripts[@]}"; do
-              echo "- $failed_script"
-            done
-            exit 1 # Exit with failure status
-          fi
-
-  test-reviewer-permissions:   
+  test-reviewer-permissions:
     runs-on: ubuntu-latest
     env:  
-      PR_CREATOR: automation-bot      
-      INVALID_REVIEWER: "4k4xs4pH1r3-2"  
+      PR_CREATOR: automation-bot # Use the same user for all PR creation tests
+      INVALID_REVIEWER: "4k4xs4pH1r3-2"  # Replace with an invalid reviewer name
 
     steps:
       - name: Harden Runner
-        uses: step-security/harden-runner@v2.8.0 
+        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
         with:
           egress-policy: audit
+
       - name: Checkout Code
-        uses: actions/checkout@v3.6.0 
-      - name: Install jq 
+        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+
+      - name: Install jq
         run: sudo apt-get install -y jq
 
       - name: Verify working directory
@@ -133,41 +110,35 @@ jobs:
         run: ls -la ./.github/workflows/scripts
 
       - name: Check if test script exists
-        run: test -f ./.github/workflows/scripts/enforce-branch-sequence-test.sh && echo "File exists" || echo "File does not exist"                      
+        run: test -f ./.github/workflows/scripts/enforce-branch-sequence-test.sh && echo "File exists" || echo "File does not exist"        
 
       - name: Make tests scripts executable
         run: |
+          chmod +x ./.github/workflows/scripts/common_functions.sh
           chmod +x ./.github/workflows/scripts/enforce-branch-sequence-test.sh
-          chmod +x ./.github/workflows/scripts/common_functions.sh                      
-          chmod +x ./.github/workflows/scripts/07-pr-creation-gtcrais.sh
+          chmod +x ./.github/workflows/scripts/01-direct-push-master.sh
+          chmod +x ./.github/workflows/scripts/02-direct-push-staging.sh
+          chmod +x ./.github/workflows/scripts/03-direct-push-aws-dev.sh
+          chmod +x ./.github/workflows/scripts/04-pr-any-to-aws-dev.sh    
+          chmod +x ./.github/workflows/scripts/05-pr-aws-dev-to-staging.sh          
+          chmod +x ./.github/workflows/scripts/06-pr-staging-to-master.sh    
+          chmod +x ./.github/workflows/scripts/07-pr-creation-gtcrais.sh 
           chmod +x ./.github/workflows/scripts/08-pr-creation-ctllaw.sh
           chmod +x ./.github/workflows/scripts/09-add-invalid-reviewer.sh
           chmod +x ./.github/workflows/scripts/10-approval-merge-permissions.sh
 
       - name: Run Test Cases
         run: |
-          failed_scripts=() 
-          for i in {7..10}; do  
-            script="0${i}-*.sh" 
-            if [ -f "$script" ]; then
-              echo "Running: $script"
-              ENFORCE_BRANCH_SEQUENCE_FILE="$GITHUB_WORKSPACE/.github/workflows/enforce-branch-sequence.yml" 
-              if ! bash "$script" "$ENFORCE_BRANCH_SEQUENCE_FILE"; then  
-                echo "Error: $script failed. Check the script output for details."
-                failed_scripts+=("$script") 
-              else
-                echo "Success: $script passed."  
-              fi
-            else
-              echo "Skipping: $script not found."  
-            fi
-          done
-
-          # Report failures at the end (if any)
-          if [ "${#failed_scripts[@]}" -gt 0 ]; then
-            echo "Errors found in the following scripts:"
-            for failed_script in "${failed_scripts[@]}"; do
-              echo "- $failed_script"
-            done
-            exit 1 # Exit with failure status
+          set -e  # Enable exit on error
+          if ! ./.github/workflows/scripts/01-direct-push-master.sh &&
+             ! ./.github/workflows/scripts/02-direct-push-staging.sh &&
+             ! ./.github/workflows/scripts/03-direct-push-aws-dev.sh &&
+             ! ./.github/workflows/scripts/04-pr-any-to-aws-dev.sh &&
+             ! ./.github/workflows/scripts/05-pr-aws-dev-to-staging.sh &&
+             ! ./.github/workflows/scripts/06-pr-staging-to-master.sh &&
+             ! ./.github/workflows/scripts/07-pr-creation-gtcrais.sh &&
+             ! ./.github/workflows/scripts/08-pr-creation-ctllaw.sh &&
+             ! ./.github/workflows/scripts/09-add-invalid-reviewer.sh &&
+             ! ./.github/workflows/scripts/10-approval-merge-permissions.sh; then
+            echo "One or more test cases failed."
           fi
